FROM ubuntu

RUN apt update -y \
  && apt install -y \
    git \
    python \
    python2.7 \
    nodejs

RUN git clone https://github.com/juj/emsdk.git \
      && cd emsdk \
      && ./emsdk install latest \
      && ./emsdk activate latest

